services:

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    #network_mode: host
    restart: always
    user: "1000:1000"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - CLOUDFLARE_API_TOKEN=$CF_TOKEN # pls adjust
      - DOMAINS=*.$MY_DOMAIN # pls adjust; a list of fully qualified domain names separated by commas
      - PROXIED=true # if true, instructs Cloudflare to cache webpages on your machine and hide its actual IP addresses
      - TZ=America/Detroit
      - IP6_PROVIDER=none # disbale IPv6
